#! /usr/bin/env python

"""
Test runner for the treescore application

Usage:
    judge --fname=<f> --images=<p> [--save] [--width=<w>] [--prefix=<pf>]

Options:
    --fname=<f>     Name of the colorpicker file [default: colors.data]
    --images=<p>    Path to the image(s) to process
    --width=<w>     Width to resize images go [default: 500]
    --save          Save putput images
    --prefix=<pf>   Prefix for image files [default: tmp]
"""


__version__ = "0.0.1"

from docopt import docopt
import glob
import treescore


def main(args):
    fnames = glob.glob(args['--images'])
    picker = treescore.ColorPicker.from_file(args['--fname'])

    for fname in fnames:
        scores, images = treescore.judge.score(
            fname, picker, width=int(args['--width']), images=True)

        if args['--save']:
            treescore.judge.utils.save_images(images, args['--prefix'])

        treescore.judge.utils.display_images(images)
        print('{} {}'.format(fname, scores))


if __name__=="__main__":
    args = docopt(__doc__, version='Judge %s' % __version__ )
    main(args)


